### ISSUE TITLE
doesn't work for npm run watch

### ISSUE THREAD

**Issue by sjatkins** [richard-lopes/webpack-example#3]
> webpack-example@0.0.1 watch /data/work/webpack-example
> webpack-dev-server --port 8091 --hot --inline --progress --colors

 70% 2/2 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8091
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:84:10)

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! webpack-example@0.0.1 watch: `webpack-dev-server --port 8091 --hot --inline --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-example@0.0.1 watch script 'webpack-dev-server --port 8091 --hot --inline --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 8091 --hot --inline --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/work/webpack-example/npm-debug.log

**Comment by sjatkins** [comment]
oops.  my bad.  Forgot to reinstall/rebuild after flipping the port.
